name: kikuri-dev

volumes:
  kikuri-pg:
    name: 'kikuri-pg-dev'

services:
  postgres:
    container_name: kikuri-pg-container
    ports:
      - "5432:5432"
    image: 'postgres'
    volumes:
      - 'kikuri-pg:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: 'kikuri'
      POSTGRES_USER: 'kikuri'
      POSTGRES_DB: 'kikuri'
    restart: 'on-failure'

  redis:
    container_name: kikuri-redis-container
    ports:
      - "6379:6379"
    image: 'redis'
    command: redis-server --requirepass kikuri
    restart: 'on-failure'