name: daemon-dev

volumes:
  daemon-pg:
    name: 'daemon-pg-dev'

services:
  postgres:
    container_name: daemon-pg-container
    ports:
      - "5432:5432"
    image: 'postgres'
    volumes:
      - 'daemon-pg:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: 'daemon'
      POSTGRES_USER: 'daemon'
      POSTGRES_DB: 'daemon'
    restart: 'on-failure'

  redis:
    container_name: daemon-redis-container
    ports:
      - "6379:6379"
    image: 'redis'
    command: redis-server --requirepass daemon
    restart: 'on-failure'