name: Unit Tests

on:
  push:
    branches:
      - '*'
    paths:
      - '**.go'
      - '.github/workflows/**'

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: Run tests
        run: |
          go test -v -timeout 300s -cover ./...
